"""add sync_branch to repository

Revision ID: aeb7ed5ba7b9
Revises: b58d6200bca9
Create Date: 2026-05-30 09:20:25.838070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb7ed5ba7b9'
down_revision: Union[str, None] = 'b58d6200bca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('repository', sa.Column('sync_branch', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'sync_branch')
    op.alter_column('conversation', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
