"""add mode to conversation and name to user

Revision ID: b58d6200bca9
Revises: 34d19c8024d5
Create Date: 2026-05-29 19:20:27.591551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58d6200bca9'
down_revision: Union[str, None] = '34d19c8024d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('mode', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('conversation', 'mode')
    # ### end Alembic commands ###
